### PR TITLE
Make a standalone archive

### PR DESCRIPTION
**Pull request by thom4parisot**
Like at any crowded event, Wifi is expected to be terrible, so we should expect people to be able to git-download the repo.
This means we can't rely on rawgithub.

We also can't assume people will have git installed. We should not forget to bring USB flash drive.

### CODE REVIEW

**Comment by thom4parisot** [comment]
Ok then bower + gh-pages so as they can fetch this branch to work locally.

**Comment by DavidBruant** [comment]
> Wifi is expected to be terrible

?

**Comment by DavidBruant** [comment]
All previous years, it really was unreliable. I don't expect things to get better with twice more people this year than last years :-/

**Comment by thom4parisot** [comment]
Demo here: http://oncletom.github.io/SeeYouLaterElevator/

**Pull request merged**
